import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/providers/modal-provider";
import { ToasterProvider } from "@/providers/toast-provider";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My e-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToasterProvider />
          <ModalProvider />
          {children}
          <Carousel>
            <CarouselContent>
              <CarouselItem className="basis-1/3">item</CarouselItem>
              <CarouselItem className="basis-1/3">item</CarouselItem>
              <CarouselItem className="basis-1/3">item</CarouselItem>
              <CarouselNext />
              <CarouselPrevious />
            </CarouselContent>
          </Carousel>
        </body>
      </html>
    </ClerkProvider>
  );
}
